version: "3"

services:
  gitlab:
    image: "gitlab/gitlab-ce"
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://gitlab.shikun.icu"
        nginx["ssl_certificate"] = "/etc/gitlab/ssl/gitlab.shikun.icu.crt"
        nginx["ssl_certificate_key"] = "/etc/gitlab/ssl/gitlab.shikun.icu.key"
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - "/srv/gitlab/config:/etc/gitlab"
      - "/srv/gitlab/ssl:/etc/gitlab/ssl"
      - "/srv/gitlab/logs:/var/log/gitlab"
      - "/srv/gitlab/data:/var/opt/gitlab"
