default:
  tags:
    - docker1

stages:
  - lint

lint:
  image: python
  stage: lint
  script:
    - pip3 install ansible ansible-lint
    - ansible-lint
  variables:
    ANSIBLE_CONFIG: ./ansible.cfg
