---
- name: oh-my-zsh
  hosts: all
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ ansible_user }}"
          oh_my_zsh:
            plugins:
              - git
              - z

- name: common plays
  hosts: all
  roles:
    - privilege
    - timesync
    - package
    - dotfiles
    - docker
