---
- hosts:
    - server
    - pi

  tasks:
    - name: make sure wheel group is present
      become: yes
      group:
        name: wheel
        state: present

    - name: allow wheel group to have passwordless sudo
      become: yes
      lineinfile:
        dest: /etc/sudoers
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        state: present
        validate: "visudo -cf %s"

    - name: add sudoers users to wheel group
      become: yes
      user:
        name: "{{ ansible_user }}"
        groups: wheel
        append: yes
        state: present

    - name: make sure ntp is installed
      become: yes
      ansible.builtin.apt:
        name: ntp
        state: latest

    - name: make sure ntp service is started
      become: yes
      ansible.builtin.service:
        name: ntp
        state: started
        enabled: yes

    - name: set timezone
      become: yes
      community.general.timezone:
        name: Asia/Shanghai

    - name: update using apt
      become: yes
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes
        upgrade: "full"

    - name: install packages
      become: yes
      ansible.builtin.package:
        name:
          - docker.io
          - docker-compose
          - vim
          - neovim
          - tmux
          - zsh
          - fish
          - python
          - python3-pip
          - nodejs
          - yarnpkg
          - cron-apt
          # 可以通过 $hostname.local 访问本地设备
          - avahi-daemon
        state: latest

    - name: install docker-py using pip
      become: yes
      pip:
        name: docker
        state: latest

    - name: start docker service
      become: yes
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: copy service files
      copy:
        src: "{{ playbook_dir }}/stuff/services"
        dest: "~"

    - name: start netdata service with docker-compose
      become: yes
      community.docker.docker_compose:
        project_src: "/home/{{ ansible_user }}/services/netdata"
        state: present
        pull: yes
