---
- name: oh-my-zsh
  hosts: all
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ ansible_user }}"
          oh_my_zsh:
            plugins:
              - fzf
              - git
              - z

- name: common plays
  hosts: all
  roles:
    - dotfiles
    - package
    - timesync
    - docker

  tasks:
    - name: check if reboot is required
      become: yes
      stat:
        path: /var/run/reboot-required
      register: reboot_file

    - reboot:
      become: yes
      when: reboot_file.stat.exists
