---
- name: common plays
  hosts: all
  roles:
    - dotfiles
    - package
    - timesync
    - docker

  tasks:
    - name: check if reboot is required
      become: yes
      stat:
        path: /var/run/reboot-required
      register: reboot_file

    - name: reboot if required
      reboot:
      become: yes
      when: reboot_file.stat.exists
