remote:
  hosts:
    aws:
      ansible_user: ubuntu
    aws1:
      ansible_user: ubuntu
    linode:
      ansible_user: shikun
    oracle:
      ansible_user: ubuntu
    oracle1:
      ansible_user: ubuntu
  vars:
    is_remote: yes

home:
  hosts:
    runner:
    gitlab:
      ansible_port: 222
    nginx:
      ansible_port: 222
    npm:
    nuc:
      ansible_user: root
    workstation:
  vars:
    ansible_user: shikun
    ansible_ssh_private_key_file: ~/.ssh/home_id_rsa
