remote:
  hosts:
    aws:
      ansible_user: ubuntu
    aws1:
      ansible_user: ubuntu
    linode:
      ansible_user: shikun
    oracle:
      ansible_user: ubuntu
    oracle1:
      ansible_user: ubuntu
    gcp:
      ansible_user: shikun
  vars:
    is_remote: yes

home:
  hosts:
    node[1:4]:
    pi[1:4]:
      ansible_user: ubuntu
    nextcloud:
    runner:
    gitlab:
      ansible_port: 222
    nginx:
      ansible_port: 222
    npm:
    nuc:
      ansible_user: root
    pve:
      ansible_user: root
    workstation:
  vars:
    ansible_user: shikun
    ansible_ssh_private_key_file: ~/.ssh/home_id_rsa
