remote:
  hosts:
    aws:
      ansible_user: ubuntu
    aws1:
      ansible_user: ubuntu
    linode:
      ansible_user: shikun
    oracle:
      ansible_user: ubuntu
    oracle1:
      ansible_user: ubuntu
    gcp:
      ansible_user: shikun
  vars:
    is_remote: yes

home:
  hosts:
    pi[1:4]:
      ansible_user: ubuntu
    workstation:
      ansible_user: shikun
      ansible_port: 222
    nginx:
      ansible_user: shikun
      ansible_port: 222
    nuc:
      ansible_user: root
  vars:
    ansible_ssh_private_key_file: ~/.ssh/home_id_rsa
