pi:
  hosts:
    pi[1:4]:
      ansible_user: ubuntu

remote:
  hosts:
    aws:
      ansible_user: ubuntu
    linode:
      ansible_user: shikun
    oracle:
      ansible_user: ubuntu
  vars:
    is_remote: yes

home:
  hosts:
    10.10.11.[56:60]:
    10.10.11.67:
    10.10.11.68:
    gitlab:
    nginx:
    npm:
    workstation:
  vars:
    ansible_user: shikun
    ansible_ssh_private_key_file: ~/.ssh/home_id_rsa
