remote:
  hosts:
    oracle:
      ansible_host: oracle.vps.shikun.icu
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/oracle.key
    oracle1:
      ansible_host: oracle1.vps.shikun.icu
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/oracle1.key

pi:
  hosts:
    10.10.0.[3:6]:
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/home_id_rsa

home:
  hosts:
    gitlab-runner:
      ansible_host: 10.10.10.4
      ansible_user: shikun
      ansible_ssh_private_key_file: ~/.ssh/home_id_rsa

cluster:
  hosts:
    cluster-proxy:
      ansible_host: 10.10.0.30
      ansible_user: shikun
      ansible_ssh_private_key_file: ~/.ssh/home_id_rsa
    10.10.0.[31:33]:
      ansible_user: shikun
      ansible_ssh_private_key_file: ~/.ssh/home_id_rsa
    10.10.0.[41:45]:
      ansible_user: shikun
      ansible_ssh_private_key_file: ~/.ssh/home_id_rsa
    10.10.0.[50:53]:
      ansible_user: shikun
      ansible_ssh_private_key_file: ~/.ssh/home_id_rsa
