- name: set authorized key taken from file
  become: yes
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/home_id_rsa.pub') }}"

- name: make sure wheel group is present
  become: yes
  group:
    name: wheel
    state: present

- name: allow wheel group to have passwordless sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    state: present
    validate: "visudo -cf %s"

- name: add sudoers users to wheel group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: wheel
    append: yes
    state: present
