- name: set timezone
  become: yes
  community.general.timezone:
    name: Asia/Shanghai

- name: sync timesyncd.conf file
  become: yes
  ansible.builtin.synchronize:
    src: "stuff/config-file/timesyncd.conf"
    dest: /etc/systemd/timesyncd.conf
  when: is_remote is not defined

- name: make sure systemd-timesyncd service is restarted
  become: yes
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted
    enabled: yes
  when: is_remote is not defined
