- name: install docker-py using pip
  become: yes
  pip:
    name: docker
    state: latest

- name: start docker service
  become: yes
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
